//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReCountant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Balance_TransactionParty
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.DateTime> Time_Of_Entry { get; set; }
        public string Invoice_No { get; set; }
        public Nullable<int> Account_Id { get; set; }
        public Nullable<long> Transaction_Party { get; set; }
        public Nullable<int> Company_Id { get; set; }
        public string Currency { get; set; }
        public Nullable<double> Amount_TC { get; set; }
        public Nullable<double> Exchange_Rate { get; set; }
        public Nullable<double> Amount_LC { get; set; }
        public string Description { get; set; }
        public Nullable<double> Debit { get; set; }
        public Nullable<double> Credit { get; set; }
        public Nullable<double> Net { get; set; }
        public Nullable<long> Userid { get; set; }
    
        public virtual D_Company D_Company { get; set; }
        public virtual D_Supplier D_Supplier { get; set; }
    }
}
