//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReCountant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Balance_Installments
    {
        public int Id { get; set; }
        public Nullable<double> Due_Amount { get; set; }
        public Nullable<double> Received_Amount { get; set; }
        public Nullable<double> Net { get; set; }
        public Nullable<double> Balance { get; set; }
        public Nullable<long> Transaction_Party { get; set; }
        public Nullable<int> Inst_Id { get; set; }
        public Nullable<int> Plot_id { get; set; }
        public Nullable<int> InstRece_Id { get; set; }
    }
}
