//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReCountant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class D_Company
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Contact_Information { get; set; }
        public string NTN { get; set; }
        public string STRN { get; set; }
        public string Residential_Status { get; set; }
        public string Filer_NonFiler { get; set; }
        public string Individual_AOP_Company { get; set; }
        public string Supply_Chain_Role { get; set; }
        public string Business { get; set; }
        public string EPZ { get; set; }
        public Nullable<int> REP { get; set; }
    }
}
