//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReCountant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class D_Land_RealEstate
    {
        public int Id { get; set; }
        public Nullable<int> Land_Id { get; set; }
        public Nullable<int> Company_Id { get; set; }
        public Nullable<long> Userid { get; set; }
    }
}
