//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReCountant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class D_Phase
    {
        public int Id { get; set; }
        public Nullable<int> Project_Id { get; set; }
        public string Phase { get; set; }
        public string Phase_Code { get; set; }
    }
}
