//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReCountant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class D_Plot_Booking
    {
        public int Id { get; set; }
        public Nullable<long> Customer_Id { get; set; }
        public Nullable<int> Plot_Id { get; set; }
        public Nullable<System.DateTimeOffset> Agreement_Date { get; set; }
        public Nullable<double> Plot_Value { get; set; }
    }
}
