//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReCountant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class D_Project_Specs
    {
        public int Id { get; set; }
        public Nullable<int> Project { get; set; }
        public Nullable<int> Percentage { get; set; }
        public Nullable<int> Payment_To_Be_Receive_By { get; set; }
        public Nullable<int> REA { get; set; }
        public Nullable<int> REP { get; set; }
        public Nullable<long> Userid { get; set; }
    }
}
