//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReCountant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class F_Financial_Transactions
    {
        public long Id { get; set; }
        public Nullable<System.DateTime> Document_Date { get; set; }
        public string Voucher_Number { get; set; }
        public Nullable<System.DateTime> DateTime_Of_Entry { get; set; }
        public string Voucher_Type { get; set; }
        public string Reference_Number { get; set; }
        public string Transaction_Document_Number { get; set; }
        public Nullable<int> Account_Id { get; set; }
        public Nullable<long> Supplier_Id { get; set; }
        public Nullable<long> Customer_Id { get; set; }
        public Nullable<long> Employee_Id { get; set; }
        public Nullable<long> Owner_Id { get; set; }
        public Nullable<int> Company_Id { get; set; }
        public Nullable<long> Transaction_Party { get; set; }
        public Nullable<int> Plot { get; set; }
        public Nullable<int> Land { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<double> Amount_TC { get; set; }
        public Nullable<double> Exchange_Rate { get; set; }
        public double Amount_LC { get; set; }
        public string Description { get; set; }
        public Nullable<double> Debit { get; set; }
        public Nullable<double> Credit { get; set; }
        public Nullable<double> Net { get; set; }
        public Nullable<int> ResponsibilityCenter_Id { get; set; }
        public Nullable<int> Function_Id { get; set; }
        public Nullable<int> Project { get; set; }
        public Nullable<int> REA { get; set; }
        public Nullable<int> REP { get; set; }
        public Nullable<int> Space_Type { get; set; }
        public string Knocking_Off { get; set; }
        public Nullable<long> Userid { get; set; }
        public string Currency { get; set; }
        public string Product { get; set; }
        public string Region { get; set; }
        public string Bank_Account_Number { get; set; }
        public string Purchase_Order { get; set; }
        public string Recording_Index { get; set; }
        public Nullable<double> Rate { get; set; }
        public string Uom { get; set; }
    }
}
