//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReCountant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Installment_Plan
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<double> Amount_TC { get; set; }
        public Nullable<double> Exchange_Rate { get; set; }
        public Nullable<double> Amount_LC { get; set; }
        public Nullable<long> Supplier_Id { get; set; }
        public Nullable<long> Customer_Id { get; set; }
        public Nullable<long> Employee_Id { get; set; }
        public Nullable<long> Owner_Id { get; set; }
        public string Description { get; set; }
        public Nullable<int> Plot_Id { get; set; }
        public Nullable<int> Nth_Installment { get; set; }
        public Nullable<System.DateTime> Due_Date { get; set; }
        public Nullable<int> Transaction_Party { get; set; }
        public Nullable<int> REP { get; set; }
        public Nullable<System.DateTime> Payment_Date { get; set; }
        public Nullable<int> Project_Id { get; set; }
        public Nullable<long> Userid { get; set; }
        public string Category { get; set; }
        public string Currency { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<bool> Rec_Revenue_Status { get; set; }
    }
}
