//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReCountant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LandPlotMapping
    {
        public int Id { get; set; }
        public string Land { get; set; }
        public string Block { get; set; }
        public string Plot { get; set; }
        public Nullable<int> Userid { get; set; }
    }
}
