//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReCountant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RealEstate_Activity
    {
        public int Id { get; set; }
        public string RealEstate_Activites { get; set; }
        public Nullable<int> RealEstate_Activites_L2 { get; set; }
    }
}
