//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReCountant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REP
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string CNIC { get; set; }
        public string Address { get; set; }
        public string Contact { get; set; }
        public string Email { get; set; }
        public string Gender { get; set; }
        public string NTN { get; set; }
        public string STRN { get; set; }
        public string Residential_Status { get; set; }
        public Nullable<int> Industry { get; set; }
        public Nullable<int> Supply_Chain_Role { get; set; }
        public Nullable<bool> Filer_NonFiler { get; set; }
        public string Individual_AOP_Company { get; set; }
        public string Bank_Account { get; set; }
        public string Bussiness { get; set; }
        public string EPZ { get; set; }
        public Nullable<long> Userid { get; set; }
    }
}
