//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReCountant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction_Rules
    {
        public int Id { get; set; }
        public int COA { get; set; }
        public string Credit_Debit { get; set; }
        public int Transaction_Type_Id { get; set; }
    }
}
